# -*- coding: utf-8 -*-
"""mywebscraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16mnLZn9vq1I8Xr0g9QHjYUmafBHZ8NLv
"""

from bs4 import BeautifulSoup
import requests, openpyxl

excel=openpyxl.Workbook()

sheet=excel.active

sheet.title="Top Rated Movies on IMDB"

print(excel.sheetnames)

sheet.append(["Rank","Name","Year","Rating"])

source = requests.get('https://www.imdb.com/chart/top/')

source.raise_for_status()#if url is invalid

soup = BeautifulSoup(source.text,'html.parser')

movies = soup.find('tbody',class_="lister-list").find_all('tr')

#print(len(movies))

for movie in movies:
  name = movie.find('td',class_="titleColumn").a.text
  rank = movie.find('td',class_="titleColumn").get_text(strip=True).split('.')[0]#strips all spaces n newline characters and prints in single line
  year = movie.find('td',class_="titleColumn").span.text.strip('()')
  rating = movie.find('td',class_="ratingColumn imdbRating").strong.text
  print(rank,name,year,rating)
  sheet.append([rank,name,year,rating])

excel.save("Imdb Movie Ratings.xlsx")